name: Deploy StorageApp Backend

on:
  push:
    branches:
      - main        # Trigger workflow on push to main branch
    paths:
      - 'server/**' # Only run if changes are in client/ folder
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_HOST: 54.236.246.83
      SSH_USER: ubuntu

    steps:
      # 1. Setup SSH key and known_hosts
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          # Add server host key so SSH does not ask for confirmation
          ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts

      # 2. Deploy to remote server
      - name: Deploy backend on EC2
        run: |
          ssh "${SSH_USER}@${SSH_HOST}" 'bash -s' << 'EOF'
            set -e

            cd /home/ubuntu/File-Storage/

            # Prevent git pull conflicts
            git reset --hard
            git pull

            # Load Node / npm (required because GitHub SSH is non-interactive)
            export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v24.12.0/bin

            # 3. Navigate into the SERVER folder
            cd server
            
            echo "Installing backend dependencies (npm ci)..."
            npm i

            echo "Reloading PM2 app..."
            pm2 reload storageApp

            echo "Backend Deployed Successfully..."
          EOF