name: Deploy StorageApp Backend

on:
  push:
    branches:
      - main        # Trigger workflow on push to main branch
    paths:
      - 'server/**' # Only run if changes are in client/ folder
  workflow_dispatch:  # Allow manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Execute Remote SSH Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 54.236.246.83
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          script: |
            set -e

            # 1. Manually add the NVM bin directory to the PATH
            export PATH=$PATH:/home/ubuntu/.nvm/versions/node/v24.12.0/bin

            # 2. Navigate to the project
            cd /home/ubuntu/File-Storage/

            # 3. Pull the latest code
            echo "Pulling latest code from master..."
            git pull origin master

            # 4. Install production dependencies
            echo "Installing dependencies..."
            npm ci --production --no-audit --no-fund

            # 5. Smart Restart (Reload if running, start if not)
            echo "Reloading StorageApp with PM2..."
            pm2 reload storageapp 
            

            echo "✅ StorageApp Backend Deployed Successfully!"
